Adding Addon Templating Engine + Web App Routing
Azure/draft pull request #125
Opened 2022-07-27 21:38 UTC by imiller31

This PR aims to serve as the new `update` command and implements more idiomatic templating and patterns.

With this change, arbitrary CRDs can be generated with user inputs. This templating strategy should unify with Builders and DeployTypes in the future.

2022-08-08 15:13 UTC, davidgamero requested changes

2022-08-09 15:52 UTC, imiller31 commented on pkg/config/addon_config.go
> +package config
sync'd offline

2022-08-12 18:32 UTC, davidgamero approved these changes
LGTM

2022-08-12 18:40 UTC, davidgamero commented
yikes got the flag issue on the integration tests again

2022-08-12 20:01 UTC, davidgamero commented
rebased to #136 due to signed commits issue

2022-08-12 20:01 UTC, closed without merging