Bug Fix: destination path duplication fix
Azure/draft pull request #204
Opened 2023-04-07 16:18 UTC by aamgayle

# Description

Merged PR between 
https://github.com/Azure/draft/pull/200
and
https://github.com/Azure/draft/pull/203

Fixes # (issue)
Path duplication issue when generating workflows (i.e .github/workflows/.github/workflows being where workflows are placed)
Feature # (details)
Fixes the bug and adds more unit tests

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Is it a  breaking change which will impact consuming tool(s).

- [x] Unit tests performed locally and integration tests performed successfully 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-04-07 17:32 UTC, bfoley13 commented on pkg/embedutils/embedutil.go
> +func EmbedFStoMapWithFiles(embedFS fs.FS, path string) (map[string]fs.DirEntry, error) {
You can simplify with walk: https://pkg.go.dev/path/filepath#Walk

2023-04-07 20:42 UTC, davidgamero requested changes

2023-04-07 20:42 UTC, davidgamero commented on pkg/workflows/workflows_test.go
> +  //test for invalid k8sObj
nit: indentation

2023-04-07 20:42 UTC, davidgamero commented on pkg/workflows/workflows_test.go
> +	assert.NotNil(t, setHelmContainerImage("", "testImage", testTemplateWriter))
do all these sub-tests have some shared state? otherwise we could just break this up into several smaller tests instead of one big one

2023-04-07 20:42 UTC, davidgamero commented on pkg/workflows/workflows_test.go
> +	_, err = w.loadConfig("helm")
could this be done using a test struct array loop instead of using so many copies of the same lines?

2023-04-07 20:42 UTC, davidgamero commented on pkg/workflows/workflows_test.go
> +	_, err = w.loadConfig("helm")
like using subtests https://blog.logrocket.com/a-deep-dive-into-unit-testing-in-go/#:~:text=To%20test%20each%20case%2C%20we%20need%20to%20iterate,run%20the%20test%20again%2C%20it%20will%20pass%20successfully%3A

2023-04-07 20:42 UTC, davidgamero commented on test/gen_integration.sh
> +export WORKFLOWS_PATH=.github/workflows
this is a great change

2023-04-10 15:31 UTC, bfoley13 approved these changes
Looks good!

2023-04-10 17:12 UTC, davidgamero approved these changes
lgtm

2023-04-10 17:12 UTC, merged