Adding the client interface and unit tests for getTenantID func
Azure/draft pull request #262
Opened 2024-04-03 06:40 UTC by Vidya2606

# Description

Added the client interface and unit tests for getTenantID func

Fixes # (issue)
Feature # (details)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Is it a  breaking change which will impact consuming tool(s).

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-04 14:52 UTC, bfoley13 commented on pkg/providers/azure_test.go
> +func TestGetTenantId(t *testing.T) {
We should have tests around the different errors/scenarios possible within the getTenantId and listTenant clients

2024-04-04 14:56 UTC, bfoley13 commented on pkg/providers/azure.go
> +	AzTenantClient    azTenantClient
if were going to have many interfaces associated with the az client, we should pull the clients into a single struct and have it be initialized.

Have an AzClient struct that will contain the sub tenantClient, appsClient, etc interfaces.

2024-04-12 17:24 UTC, davidgamero requested changes

2024-04-12 18:41 UTC, davidgamero commented on cmd/setup-gh.go
> +			sc.AzClient.AzTenantClient = client
nevermind this is a struct type not a pointer

2024-04-12 19:32 UTC, davidgamero approved these changes
lgtm

2024-04-12 20:30 UTC, Tatsinnit approved these changes
THank you and looks good to me! ☕️🙏❤️

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHZ4Z3NqcDRhd3AwZ2o0dWVlOWh1cTV4cGx0Ym90djFsNG95eDhvZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/aCatQNctAK7PC1H4zh/giphy.gif)

2024-04-12 20:36 UTC, bfoley13 approved these changes

2024-04-12 21:00 UTC, merged